import type from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Search from '../app/components/utility/base/search'
import Link from 'next/link'

import { NextPageWithLayout } from './page';
import PrimaryLayout from '../app/components/layouts/primary/PrimaryLayout';



const Home: NextPageWithLayout = () => {
  const { locale } = useRouter();

  return (
    < >
      <section> 
    <Image
        src="/Google_2015_logo.svg"
        alt="Google Logo"
        width={272}
        height={92}
        priority
      />

      <Search />


      <p>
        Google offered in:{' '}
        <Link href="/" locale={locale === 'en' ? 'fr' : 'en'}>
          <a className="underline text-blue-600"> Français</a>
        </Link>
      </p>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}> </main>

      <footer className={styles.footer}> </footer>
      </section>
    </>
  )
}

export default Home



Home.getLayout = (page) => {
  return <PrimaryLayout>{page}</PrimaryLayout>;
} 